#!/bin/bash
#
# Copyright 2018 Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

PACKER_IMAGE=$(sudo ls $TMP_MOUNT_PATH/output-qemu)
DIB_UID=$(id -un)
DIB_GUID=$(id -gn)
sudo mv $TMP_MOUNT_PATH/output-qemu/${PACKER_IMAGE} image.qcow2
sudo chown $DIB_UID:$DIB_GUID image.qcow2
